### ISSUE TITLE
[bug]:  --overwrite-firebase-options flag not working 

### ISSUE THREAD

**Issue by qwadrox** [invertase/flutterfire_cli#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.10.2

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale
    en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for -- iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

### Description

`--overwrite-firebase-options` Seems to not have any effect. After setting this option still asks:  do you want to override it?

Example output 
```bash
mateboros@Mates-MacBook-Pro my_catalog_app % flutterfire configure  --out="lib/firebase_options_dev.dart" --platforms="ios" --ios-bundle-id="com.example.myCatalogApp.dev" --ios-out="ios/dev"  --overwrite-firebase-options
✔ You have to choose a configuration type. Either build configuration (most likely choice) or a target set up. · Build configuration      
✔ Please choose one of the following build configurations · Debug-dev                                                                     
? Generated FirebaseOptions file /Users/mateboros/Documents/Github/my_catalog_app/lib/firebase_options_dev.dart already exists, do you want to override it? (y/n) › yes
```

### Steps to reproduce

SAMPLE: https://github.com/qwadrox/my_catalog_app

1. Run: `flutterfire configure  --out="lib/firebase_options_dev.dart" --platforms="ios" --ios-bundle-id="com.example.myCatalogApp.dev" --ios-out="ios/dev"  --overwrite-firebase-options`

### Expected behavior

Should not ask to override the file. It should just override.

**Comment by russellwheatley** [comment]
@qwadrox - Thanks, I'll get this looked at. In the mean time, you can use `--yes` which ought to overwrite the file 👍

**Comment by Ssiswent** [comment]
The same, `flutterfire configure --no-overwrite-firebase-options` not work, still ask if overwrite  FirebaseOptions file.

![Image](https://github.com/user-attachments/assets/e5746f85-9330-4407-8d4e-b1c11d1d5835)

**Comment by SelaseKay** [comment]
Hi @qwadrox, are you able to reproduce this issue with flutterfire version 1.4.0? It looks like this has been resolved in the latest release.

**Comment by krushnXenlabs** [comment]
Checked this on `main` (1.4.1).

`--overwrite-firebase-options` works now.

`--no-overwrite-firebase-options` is still broken though, as mentioned by @wer-mathurin above. It still asks whether to override the file. The getter in `config.dart` returns `false` both when you pass `--no-overwrite-firebase-options` and when you pass nothing, so the "no" gets ignored and it falls back to the prompt.

I've got a fix for it, with tests: https://github.com/krushnXenlabs/flutterfire_cli/tree/fix/issue-311-no-overwrite-firebase-options

@russellwheatley  CONTRIBUTING mentions not forking, but I don't have write access to push a branch here. Would it be okay if I opened the PR from my fork? If not, could you give me access to push a branch here?
